# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20190627_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='shawn', max_length=255),
            preserve_default=False,
        ),
    ]
