# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='sent_by',
        ),
    ]
