# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20190628_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start',
            field=models.DateField(),
        ),
    ]
